### ISSUE TITLE
Nextcloud 10 support?

### ISSUE THREAD

**Issue by hunter-nl** [mfleonhardt/activitydefaults#2]
Currently the app is not supported by Nextcloud 10. Can it made compatible with Nextcloud 10?

**Comment by hregnier** [comment]
As far as i see, stable-9.1 works on nextcloud 10. I had to modify requirements, but it works.

**Comment by mfleonhardt** [comment]
Thanks for the follow-up.  I haven't really looked into NextCloud yet.  That's good to know.  I'll consider a NextCloud development branch.

Of course, feel free to fork this repo if you want to maintain the project for NextCloud yourself! ;)

**Comment by avanzella** [comment]
@hregnier 
Hello,
Could you please explain how you got stable-9.1 working on Nextcloud 10?
When trying to install I get the following error message:
_"App 'activitydefaults' could not be installed!"_
Regards

**Comment by klm46** [comment]
> As far as i see, stable-9.1 works on nextcloud 10. I had to modify requirements, but it works.

Hi there. Where to modify the requirements? I would like to use this as well in nc10 ;)

Thanks in advance

edit: do you mean the info.xml in appinfo folder?
won't work for me

**Comment by mfleonhardt** [comment]
Can you describe how you're installing and what happens when you try to install?  I was able to install into nextcloud 10 using the app store without making any modifications.

**Comment by klm46** [comment]
Hi,  i tried both ways. Via nextcloud-app-store. So checkin the checkbox of experimental appsk, then try to activate the app:
Client error response [url] https://apps.owncloud.com/CONTENT/content-files/174669-activitydefaults.tar.gz [status code] 400 [reason phrase] Bad Request
nextcloud.log:
{"reqId":"WAoWfzr5RarpArW3IOe3lAAAAAU","remoteAddr":"192.168.113.83","app":"core","message":"Client error response [url] https:\/\/apps.owncloud.com\/CONTENT\/content-files\/174669-activitydefaults.tar.gz [status code] 400 [reason phrase] Bad Request","level":3,"time":"2016-10-21T15:22:10+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"0710A9F1-0E77-45E1-B69F-B915E364C0E3"}

Than i downloaded the stabel from github and unziped it into app-folder of filesystem. no it was listet in appstore, when try to activate app following is written:
App 'activitydefaults' could not be installed!
nextcloud.log:
{"reqId":"WAoWBKEKavytobmgYxmTJgAAAAk","remoteAddr":"192.168.113.83","app":"core","message":"App 'activitydefaults' could not be installed!","level":3,"time":"2016-10-21T15:20:05+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"0710A9F1-0E77-45E1-B69F-B915E364C0E3"}

CentOS7 latest
NC latest

**Comment by hregnier** [comment]
Hi @klm46, I downloaded the stable from github and unziped it in /apps folder, just like you did. When i was on the application administration panel, nextcloud said that the app was not compatible (dependencies was not satisfiyed) and i wasnt able to click on the "activate" button. So I changed <owncloud min-version="8.2" max-version="9.1"/> to <owncloud min-version="9.1" max-version="10.0"/> in info.xml. After that, i was able to activate it after the info.xml was properly loaded (it can take few reload and time).

**Comment by mfleonhardt** [comment]
@klm46 The 400 Bad Request error sounds like a known ownCloud/CentOS/RHEL issue: https://github.com/owncloud/core/issues/25541.  If you're on a RedHat platform, you probably have to install apps manually until that issue is resolved.

I'll attempt the manual install and see how it works for me.

**Comment by klm46** [comment]
i did try to download the app manually and install it, but error like written above apeired.. so no chance for at the monent to activate this app.

**Comment by klm46** [comment]
hi @hregnier 

> Hi @klm46, I downloaded the stable from github and unziped it in /apps folder, just like you did. When i was on the application administration panel, nextcloud said that the app was not compatible (dependencies was not satisfiyed) and i wasnt able to click on the "activate" button. So I changed to in info.xml. After that, i was able to activate it after the info.xml was properly loaded (it can take few reload and time).

Whhich stable did you use? I tried exactly the same with the 9.1 - stable. without success.

**Comment by mfleonhardt** [comment]
A couple of things I noticed.  
1. I had an unmerged sync from my internal Bitbucket server.  (I do development locally and then clone it out to GitHub.)  That included the change in appinfo.xml to mark activitydefaults as owncloud 9.1 compatible.  That's now correctly merged into the stable9.1 and master branches.
2. According to https://docs.nextcloud.com/server/10/developer_manual/app/info.html, the dependency versions between owncloud and nextcloud are mapped.  The stable9.1 branch, (correctly) marked as owncloud 9.1 compatible, works in nextcloud 10 without any modification.

Edit: wrong link

**Comment by klm46** [comment]
For me the app can't be activeted within NC 10.0 and the new stable release 9.1. The debug-Log of NC says:

{"reqId":"WBBjvdAgFHdAyZmI3Zo@ngAAAAA","remoteAddr":"192.168.113.83","app":"core","message":"No update found at the ownCloud appstore for app activitydefaults","level":0,"time"
:"2016-10-26T10:05:18+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"0710A9F1-0E77-45E1-B69F-B915E364C0E3"}
{"reqId":"WBBjvdAgFHdAyZmI3Zo@ngAAAAA","remoteAddr":"192.168.113.83","app":"core","message":"App 'activitydefaults' could not be installed!","level":3,"time":"2016-10-26T10:05:
18+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"0710A9F1-0E77-45E1-B69F-B915E364C0E3"}

**Comment by mfleonhardt** [comment]
@klm46 That error message about the app store doesn't seem consistent with installing from the GitHub source.  Please try deleting the activitydefaults folder entirely, then manually re-downloading the stable9.1 branch from GitHub.  Unzip it in the app directory and it should install without any problems.

If you do have a problem, it's a different issue than the one I already fixed.  Please open a new issue and I'll take a look.
