### ISSUE TITLE
Fail to activate  Stabel 9.1 ( in Nextcloud 10) via Webfrontend

### ISSUE THREAD

**Issue by klm46** [mfleonhardt/activitydefaults#5]
Regarding to issue -> https://github.com/mfleonhardt/activitydefaults/issues/2 I'am not able to activate the stable 9.1 from github.  
- Download zip 
- extract to apps (no other activitydefaults folders there)
- chown apache:apchae
- try to activate the app via fontend (vivaldi and firefox tried)
- "Could not be installed" is written

nextcloud.log (Debug):
{"reqId":"WBBjvdAgFHdAyZmI3Zo@ngAAAAA","remoteAddr":"192.168.113.83","app":"core","message":"No update found at the ownCloud appstore for app activitydefaults","level":0,"time"
:"2016-10-26T10:05:18+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"0710A9F1-0E77-45E1-B69F-B915E364C0E3"}
{"reqId":"WBBjvdAgFHdAyZmI3Zo@ngAAAAA","remoteAddr":"192.168.113.83","app":"core","message":"App 'activitydefaults' could not be installed!","level":3,"time":"2016-10-26T10:05:
18+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"0710A9F1-0E77-45E1-B69F-B915E364C0E3"}

ServerOS
CentOS 7 latest

PHP
Version: 5.5.21
Memory Limit: 7.8 GB
Max Execution Time: 3600
Upload max size: 9.8 GB

Database
Type: mysql
Version: 5.5

**Comment by mfleonhardt** [comment]
Looks like a version compatibility problem.  Let's check a couple of things.

In the activitydefaults code, navigate to appinfo/info.xml and find the tag: info > dependencies > owncloud.  What is the value of the "max-version" attribute?

In nextcloud, navigate to Admin > Server Settings > Version.  What version of nextcloud are you running?

**Comment by klm46** [comment]
`<dependencies>
        <owncloud min-version="8.2" max-version="9.1"/>
    </dependencies>
`

`Version

10.0 (stable)`

**Comment by mfleonhardt** [comment]
I've replicated your environment and tried a couple of things and I can't reproduce those messages.  Check a couple other things:
1. Are you using git clone to install activitydefaults, or downloading a zip file?  The zip file extracts into a folder named activitydefaults-stable9.1.  Rename it to "activitydefaults."
2. After installing, make sure you give the web user ownership: `sudo chown -R apache:apache activitydefaults`

Finally, make sure previous installations were cleanly removed from the database:

``` sql
DELETE FROM oc_appconfig WHERE appid='activitydefaults'
```

**Comment by klm46** [comment]
The renaming of the folder was the problem. So i could not activate the app with ste stable9.1 in the foldername. Thank you.
